default_blacklist: "~/mepylome/data/cpg_blacklist.csv"

diagnostic_config:

  salivary_gland_tumors:
    name: "Salivary Gland Tumors"
    do_umap: true
    do_classify: true
    do_cnv: true
    version: 0.0.0
    classifier_list:
      - vtl-kbest(k=10000)-et
      - vtl-kbest(k=10000)-lr(max_iter=10000)
      # - vtl-kbest(k=10000)-rf
      # - vtl-kbest(k=10000)-svc
      # - vtl-pca_auto-lr(max_iter=10000)
      # - vtl-pca_auto-et
      # - vtl-knn(weights='distance')
    annotation_diagnosis_column: 
      - "Methylation class"
    methyl_analysis:
      analysis_dir: "~/mepylome/data/salivary_gland_tumors"
      reference_dir: "~/mepylome/data/cnv_references"
      annotation: "~/mepylome/data/salivary_gland_tumors/salivary_gland_tumors.xlsx"
      test_dir: "~/mepylome/data/new_cases"
      output_dir: "~/mepylome/outputs"
      cpgs: "450k+epic+epicv2"
      n_cpgs: 25000
      overlap: true
      cpg_blacklist: null

  # soft_tissue_tumors:
  #   name: "Soft Tissue Tumors"
  #   do_umap: true
  #   do_classify: true
  #   version: 0.0.0
  #   classifier_list:
  #     - vtl-kbest(k=10000)-et
  #     - vtl-kbest(k=10000)-lr(max_iter=10000)
  #     - vtl-kbest(k=10000)-rf
  #     - vtl-kbest(k=10000)-svc
  #     - vtl-pca_auto-lr(max_iter=10000)
  #     - vtl-pca_auto-et
  #     - vtl-knn(weights='distance')
  #   annotation_diagnosis_column: 
  #     - "Methylation_class"
  #   methyl_analysis:
  #     analysis_dir: "~/mepylome/data/soft_tissue_tumors"
  #     reference_dir: "~/mepylome/data/cnv_references"
  #     annotation: "~/mepylome/data/soft_tissue_tumors/soft_tissue_tumors.xlsx"
  #     test_dir: "~/mepylome/data/new_cases"
  #     output_dir: "~/mepylome/outputs"
  #     cpgs: "450k+epic+epicv2"
  #     n_cpgs: 25000
  #     overlap: true
  #     cpg_blacklist: null
